[2024-01-23T17:23:20.751+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: our_first_dag.greet manual__2024-01-23T17:23:15.581667+00:00 [queued]>
[2024-01-23T17:23:20.904+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: our_first_dag.greet manual__2024-01-23T17:23:15.581667+00:00 [queued]>
[2024-01-23T17:23:20.905+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 1
[2024-01-23T17:23:21.299+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): greet> on 2024-01-23 17:23:15.581667+00:00
[2024-01-23T17:23:21.370+0000] {standard_task_runner.py:60} INFO - Started process 501 to run task
[2024-01-23T17:23:21.439+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'our_first_dag', 'greet', 'manual__2024-01-23T17:23:15.581667+00:00', '--job-id', '3', '--raw', '--subdir', 'DAGS_FOLDER/loading_data_to_aws_S3.py', '--cfg-path', '/tmp/tmpk4ipdhqb']
[2024-01-23T17:23:21.474+0000] {standard_task_runner.py:88} INFO - Job 3: Subtask greet
[2024-01-23T17:23:22.358+0000] {task_command.py:423} INFO - Running <TaskInstance: our_first_dag.greet manual__2024-01-23T17:23:15.581667+00:00 [running]> on host 9924936b75b5
[2024-01-23T17:23:23.726+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='charlotte' AIRFLOW_CTX_DAG_ID='our_first_dag' AIRFLOW_CTX_TASK_ID='greet' AIRFLOW_CTX_EXECUTION_DATE='2024-01-23T17:23:15.581667+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-01-23T17:23:15.581667+00:00'
[2024-01-23T17:23:23.734+0000] {logging_mixin.py:188} INFO - Hello world!
[2024-01-23T17:23:23.736+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-01-23T17:23:23.807+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=our_first_dag, task_id=greet, execution_date=20240123T172315, start_date=20240123T172320, end_date=20240123T172323
[2024-01-23T17:23:23.910+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-01-23T17:23:24.284+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
