[2024-01-28T16:02:47.079+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: fetch_stackoverflow_data.get_stackoverflow_data scheduled__2023-03-09T00:00:00+00:00 [queued]>
[2024-01-28T16:02:47.193+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: fetch_stackoverflow_data.get_stackoverflow_data scheduled__2023-03-09T00:00:00+00:00 [queued]>
[2024-01-28T16:02:47.197+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 6
[2024-01-28T16:02:47.909+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): get_stackoverflow_data> on 2023-03-09 00:00:00+00:00
[2024-01-28T16:02:48.132+0000] {standard_task_runner.py:87} INFO - Running: ['***', 'tasks', 'run', 'fetch_stackoverflow_data', 'get_stackoverflow_data', 'scheduled__2023-03-09T00:00:00+00:00', '--job-id', '1390', '--raw', '--subdir', 'DAGS_FOLDER/loading_data_to_aws_S3.py', '--cfg-path', '/tmp/tmp9_e4payr']
[2024-01-28T16:02:48.160+0000] {standard_task_runner.py:88} INFO - Job 1390: Subtask get_stackoverflow_data
[2024-01-28T16:02:48.412+0000] {standard_task_runner.py:60} INFO - Started process 3530 to run task
[2024-01-28T16:02:48.888+0000] {task_command.py:423} INFO - Running <TaskInstance: fetch_stackoverflow_data.get_stackoverflow_data scheduled__2023-03-09T00:00:00+00:00 [running]> on host 9924936b75b5
[2024-01-28T16:02:49.184+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='charlotte' AIRFLOW_CTX_DAG_ID='fetch_stackoverflow_data' AIRFLOW_CTX_TASK_ID='get_stackoverflow_data' AIRFLOW_CTX_EXECUTION_DATE='2023-03-09T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2023-03-09T00:00:00+00:00'
[2024-01-28T16:02:50.587+0000] {python.py:201} INFO - Done. Returned value was: None
[2024-01-28T16:02:50.813+0000] {taskinstance.py:1138} INFO - Marking task as SUCCESS. dag_id=fetch_stackoverflow_data, task_id=get_stackoverflow_data, execution_date=20230309T000000, start_date=20240128T160247, end_date=20240128T160250
[2024-01-28T16:02:52.589+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 0
[2024-01-28T16:02:53.646+0000] {taskinstance.py:3280} INFO - 1 downstream tasks scheduled from follow-on schedule check
